version: '3'

services:
  db:
    container_name: postgres
    image: postgres:12.2-alpine
    restart: always
    volumes:
      - hhar_server_app_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  api:
    container_name: strapi
    image: strapi/strapi:3.0.0-beta.19.5-alpine
    environment:
      - VIRTUAL_HOST=api.${HOST}
      - NODE_ENV=${ENV}
      - DATABASE_CLIENT=${DATABASE_CLIENT}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - ${SERVER_APP_PATH}:/srv/app
    depends_on:
      - db

  web:
    build:
      context: ${CLIENT_WEB_APP_PATH}
      dockerfile: Dockerfile
    volumes:
      - ${CLIENT_WEB_APP_PATH}:/web/app
    expose:
      - 3000
    environment:
      - VIRTUAL_HOST=${HOST}
      - NODE_ENV=${ENV}
    # command: npm i && npm run dev

  nginx:
    image: jwilder/nginx-proxy:alpine
    ports:
      - ${PORT}:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - api
      - web

volumes:
  hhar_server_app_db: {}