version: '3'

services:
  db:
    container_name: postgres
    image: postgres:12.2-alpine
    restart: always
    networks:
      - main_network
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  webserver:
    container_name: webserver
    image: node:12-alpine
    working_dir: /app
    networks:
      main_network:
        aliases:
          - wld.com
    ports:
      - 9000:9000
      - 9100:9100
      - 1337:1337
      - 3000:3000
    volumes:
      - shared_volume:/app
    depends_on:
      - db
    command: yarn dev

  nginx:
    container_name: nginx
    image: nginx:alpine
    networks:
      main_network:
        aliases:
          - hhar.com
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - webserver

volumes:
  db_volume: {}
  shared_volume:
    driver: local
    driver_opts:
      type: none
      device: ${APP_ABS_PATH}
      o: bind

networks:
  main_network: