version: '3'

services:
  db:
    container_name: postgres
    image: postgres:12.2-alpine
    restart: always
    networks:
      main_network:
        aliases:
          - ${DATABASE_HOST}
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  api:
    container_name: api
    image: node:12-alpine
    working_dir: /app
    ports:
      - 9001:9001
    networks:
      main_network:
        aliases:
          - ${API_URL}
    volumes:
      - main_volume:/app
    depends_on:
      - db
    command: yarn dev:api

  webapp:
    container_name: webapp
    image: node:12-alpine
    working_dir: /app
    ports:
      - 9002:9002
    networks:
      main_network:
        aliases:
          - ${HOST_URL}
    volumes:
      - main_volume:/app
    depends_on:
      - api
    command: yarn dev:webapp

  nginx:
    container_name: nginx
    image: nginx:alpine
    networks:
     - main_network
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - webapp

volumes:
  db_volume: {}
  main_volume:
    driver: local
    driver_opts:
      type: none
      device: ${APP_ABS_PATH}
      o: bind

networks:
  main_network: